### ISSUE TITLE
I dont know how to set it up

### ISSUE THREAD

**Issue by Lunascaped** [ChrisTUth/discord-bot-webhook#1]
Where do i run the command?

**Comment by Lunascaped** [comment]
Please help

**Comment by ChrisButtermelon** [comment]
I do not see how this is an issue but alright.

it was wade to work with node if you setup node you can use npm to install this then you can include it. First you need to setup a webhook with discord
Also on the read me it shows you what you need to run it.
https://www.npmjs.com/package/discord-bot-webhook

**Comment by Lunascaped** [comment]
i already installed node and installed the package. idk how to setup

**Comment by ChrisButtermelon** [comment]
i would just go find a tutorial. you seem to not know node. (which would not be a problem with the code)
https://howtonode.org/hello-node

all you have to do for this is install the npm

then
```
var discord = require('discord-bot-webhook');
discord.hookId = 'PutHookIdHere';
discord.hookToken = 'PutTokenHere';
```

then as long as you set up the webhook correctly 

`discord.sendMessage('SomeText');`
